#!/usr/bin/env python3
"""Run every query in sql/05_analysis_queries.sql and document the results in docs/SQL_Query_Results.md."""
import re, sqlite3
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]


def run(root=ROOT, write=True):
    con = sqlite3.connect(Path(root) / "data" / "reinsurance.db")
    text = (Path(root) / "sql" / "05_analysis_queries.sql").read_text()
    blocks = re.split(r"^-- @(Q\d+)\s+", text, flags=re.M)[1:]
    out, results = ["# SQL analytical layer: query results", "",
                    "Generated by `python/run_queries.py` from `sql/05_analysis_queries.sql`. USD, valuation date 30-Sep-2026.", ""], {}
    for i in range(0, len(blocks), 2):
        qid, body = blocks[i], blocks[i + 1]
        title, sql = body.split("\n", 1)
        sql = "\n".join(l for l in sql.splitlines() if not l.startswith("-- @")).strip()
        df = pd.read_sql(sql, con)
        results[qid] = df
        out += [f"## {qid}. {title}", "", "```sql", sql, "```", "", df.to_markdown(index=False), ""]
    if write:
        (Path(root) / "docs" / "SQL_Query_Results.md").write_text("\n".join(out))
    return results


if __name__ == "__main__":
    r = run()
    print(f"{len(r)} queries executed OK")
